# config/config.yaml
output_dir: results/
seed_alignment: data/alignments/kunitz_seed_training.sto
validation_positives_fasta: data/validation_datasets/positive_validation.fasta
validation_positives_labels: data/validation_datasets/validation_labels.txt
validation_negatives_fasta: data/validation_datasets/negative_validation.fasta
validation_negatives_labels: data/validation_datasets/negative_labels.txt
swissprot_fasta: data/swissprot_database/uniprot_sprot.fasta
e_value_cutoff: 0.00001
